config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'

  resources :customers, except: :show do
    collection do
      get :blacklist
      post :add_to_blacklist
    end

    member do
      put :ban
      put :unban
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  VALID_PHONE_REGEX = /\A(\d{1,2}[\s.-])?(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/.freeze

  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true, length: { maximum: 15 }, format: { with: VALID_PHONE_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[edit update destroy ban unban]
  before_action :set_customer_by_phone, only: :add_to_blacklist

  def index
    @customers = Customer.where(blacklist: false)
  end

  def blacklist
    @customers = Customer.where(blacklist: true)
  end

  def ban
    @customer.blacklist = true
    @customer.save

    redirect_to(root_path, flash: { success: 'Customer was successfully banned.' })
  end

  def unban
    @customer.blacklist = false
    @customer.save

    redirect_to(blacklist_customers_path, flash: { success: 'Customer was successfully unbanned.' })
  end

  def add_to_blacklist
    if @customer.nil?
      @customers = Customer.where(blacklist: true)
      flash.now[:error] = "Customer was not found by phone: #{params[:phone]}"
      render(:blacklist)
    else
      @customer.blacklist = true
      @customer.save

      redirect_to(blacklist_customers_path, flash: { success: 'Customer was successfully added to blacklist.' })
    end
  end

  def new
    @customer = Customer.new
  end

  def edit; end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to(root_path, flash: { success: 'Customer was successfully created.' })
    else
      render(:new)
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to(root_path, flash: { success: 'Customer was successfully updated.' })
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to(root_path, flash: { success: 'Customer was successfully destroyed.' })
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def set_customer_by_phone
    @customer = Customer.find_by_phone(params[:phone])
  end

  def customer_params
    params.require(:customer).permit(:name, :phone, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info alert-dismissible fade show'
    when 'success' then 'alert alert-success alert-dismissible fade show'
    when 'error' then 'alert alert-danger alert-dismissible fade show'
    when 'alert' then 'alert alert-warning alert-dismissible fade show'
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def customer_actions(customer)
    return link_to('Unban', unban_customer_path(customer), method: :put) if customer.blacklist?

    <<-HTML.html_safe
      #{link_to('Edit', edit_customer_path(customer))}
       |
      #{link_to('Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' })}
       |
      #{link_to('Ban', ban_customer_path(customer), method: :put)}
    HTML
  end

  def customers_list(customers)
    return content_tag(:p, 'Customers not found') if customers.blank?

    render(partial: 'customers/table', locals: { customers: customers })
  end
end

app/views/customers/_form.html.erb
<%= bootstrap_form_for(customer) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :phone %>
  <%= f.text_area :description, rows: 10 %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/customers/_table.html.erb
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Phone</th>
    <th class="w-50">Description</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% customers.each.with_index(1) do |customer, index| %>
    <tr>
      <td><%= index %></td>
      <td><%= customer.name %></td>
      <td><%= customer.phone %></td>
      <td><%= customer.description %></td>
      <td><%= customer_actions(customer) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/customers/blacklist.html.erb
<h1>Blacklist of customers</h1>

<div class="container mb-3">
  <div class="row">
    <%= bootstrap_form_tag(url: add_to_blacklist_customers_path, layout: :inline) do |f| %>
      <%= f.text_field :phone %>
      <%= f.submit 'Add customer to blacklist', class: "btn btn-primary ml-3" %>
    <% end %>
  </div>
</div>

<%= customers_list(@customers) %>

<%= link_to('List of customers', root_path) %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<div class="row">
  <div class="col-6">
    <%= render 'form', customer: @customer %>
  </div>
</div>

<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of customers</h1>

<%= customers_list(@customers) %>

<%= link_to('New Customer', new_customer_path) %>
 |
<%= link_to('Blacklist of customers', blacklist_customers_path) %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<div class="row">
  <div class="col-6">
    <%= render 'form', customer: @customer %>
  </div>
</div>

<%= link_to 'Back', customers_path %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TetranCustomerTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div>
          <%= render(partial: 'layouts/flash_message') %>
        </div>
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>